#include "models/JAModel.h"
#include "models/model.h"

namespace budoux {
const Model& GetJAModel() {
    static Model model{
        .params = {
            {
                // param: BW1
                {{std::string("のみ"), 3058},  {std::string("以上"), 1223},  {std::string("まま"), 2830},
                 {std::string("から"), 1723},  {std::string("たま"), 2162},  {std::string("れた"), 1494},
                 {std::string("白い"), 3534},  {std::string("ちが"), -2703}, {std::string("めて"), 969},
                 {std::string("ない"), 1045},  {std::string("その"), -1066}, {std::string("では"), -518},
                 {std::string("った"), 166},   {std::string("たと"), -948},  {std::string("こと"), -1455},
                 {std::string("くれ"), 922},   {std::string("とか"), 1688},  {std::string("るの"), -1593},
                 {std::string("うな"), 513},   {std::string("たの"), -1543}, {std::string("のは"), 1277},
                 {std::string("より"), 1376},  {std::string("でも"), 667},   {std::string("とが"), -1393},
                 {std::string("しい"), 917},   {std::string("かも"), -1290}, {std::string("ック"), 631},
                 {std::string("よう"), -1620}, {std::string("んな"), 471},   {std::string("とう"), 1085},
                 {std::string("。・"), 2456},  {std::string("たら"), 949},   {std::string("気に"), -70},
                 {std::string("ても"), 623},   {std::string("利用"), 1018},  {std::string("最近"), 1515},
                 {std::string("がと"), -1545}, {std::string("この"), -1039}, {std::string("にも"), 816},
                 {std::string("もつ"), 1694},  {std::string("が、"), 1178},  {std::string("れて"), -1090},
                 {std::string("りが"), -96},   {std::string("りと"), 1198},  {std::string("んで"), -325},
                 {std::string("まだ"), 1343},  {std::string("には"), 588},   {std::string("もう"), 1414},
                 {std::string("少し"), 1375},  {std::string("とき"), 1349},  {std::string("こそ"), 1413},
                 {std::string("りも"), 1231},  {std::string("れば"), 936},   {std::string("けど"), 1014},
                 {std::string("同じ"), 1427},  {std::string("ると"), 202},   {std::string("た．"), 1736},
                 {std::string("まり"), 1018},  {std::string("いう"), 138},   {std::string("は、"), 436},
                 {std::string("とい"), -725},  {std::string("い、"), -329},  {std::string("なら"), 1251},
                 {std::string("思い"), -1273}, {std::string("て、"), 702},   {std::string("ある"), 141},
                 {std::string("って"), -196},  {std::string("で、"), 572},   {std::string("なぜ"), 1571},
                 {std::string("りに"), 356},   {std::string("りの"), -399},  {std::string("まる"), -429},
                 {std::string("れる"), 350},   {std::string("たい"), 242},   {std::string("それ"), 293},
                 {std::string("もし"), 1050},  {std::string("の間"), 1155},  {std::string("など"), 1137},
                 {std::string("いの"), -369},  {std::string("うや"), -1096}, {std::string("だけ"), 391},
                 {std::string("てい"), -522},  {std::string("とで"), 941},   {std::string("くて"), 680},
                 {std::string("んだ"), 515},   {std::string("ケー"), -781},  {std::string("いで"), -844},
                 {std::string("普段"), 655},   {std::string("のも"), 725},   {std::string("思う"), 57},
                 {std::string("えば"), 791},   {std::string("きな"), 687},   {std::string("に感"), -579},
                 {std::string("いた"), 310},   {std::string("、と"), 310},   {std::string("もの"), -538},
                 {std::string("ただ"), 398},   {std::string("のが"), 482},   {std::string("てる"), 372},
                 {std::string("大変"), 401},   {std::string("の後"), 753},   {std::string("る人"), 626},
                 {std::string("しか"), 96},    {std::string("でき"), -364},  {std::string("るで"), 252},
                 {std::string("まぁ"), 444},   {std::string("使い"), -715},  {std::string("こう"), -591},
                 {std::string("かな"), -137},  {std::string("買い"), -698},  {std::string("！！"), 322},
                 {std::string("める"), -429},  {std::string("に、"), 564},   {std::string("０円"), 304},
                 {std::string("、今"), 302},   {std::string("ージ"), 789},   {std::string("する"), -159},
                 {std::string("友達"), 625},   {std::string("クル"), 437},   {std::string("るに"), -442},
                 {std::string("やら"), 416},   {std::string("。あ"), -619},  {std::string("きり"), 449},
                 {std::string("と、"), 245},   {std::string("の上"), 589},   {std::string("ため"), 524},
                 {std::string("まで"), 160},   {std::string("か、"), -255},  {std::string("うち"), 218},
                 {std::string("なく"), 149},   {std::string("来て"), 386},   {std::string("きた"), 236},
                 {std::string("べき"), 424},   {std::string("じて"), 254},   {std::string("ぱり"), 342},
                 {std::string("んど"), -303},  {std::string("・・"), 237},   {std::string("だな"), -302},
                 {std::string("ろう"), -315},  {std::string("現在"), 281},   {std::string("。３"), 274},
                 {std::string("お店"), 199},   {std::string("てた"), 147},   {std::string("すら"), 190},
                 {std::string("いも"), -216},  {std::string("にか"), 180},   {std::string("いな"), -98},
                 {std::string("気が"), 115},   {std::string("たり"), 102},   {std::string("わら"), -71},
                 {std::string("実際"), 83},    {std::string("とに"), -20},   {std::string("も、"), 29},
                 {std::string("くさ"), -24},   {std::string("国人"), 24},    {std::string("うか"), 12},
                 {std::string("は１"), 37},    {std::string("とは"), -4}},
                // param: BW2
                {{std::string("たと"), 1475},  {std::string("とお"), -3875}, {std::string("とい"), 274},
                 {std::string("うや"), -2003}, {std::string("ない"), -2999}, {std::string("のみ"), -2622},
                 {std::string("てい"), -1296}, {std::string("であ"), -3302}, {std::string("のよ"), -838},
                 {std::string("です"), -3035}, {std::string("たま"), -2116}, {std::string("いた"), -1737},
                 {std::string("の機"), -2082}, {std::string("ので"), -921},  {std::string("でき"), -2119},
                 {std::string("には"), -1012}, {std::string("にも"), -1213}, {std::string("はじ"), -2465},
                 {std::string("、そ"), -1810}, {std::string("がと"), -1022}, {std::string("くな"), -1771},
                 {std::string("でも"), -1689}, {std::string("はな"), -331},  {std::string("のは"), -1100},
                 {std::string("ると"), -643},  {std::string("てお"), -2518}, {std::string("など"), -1807},
                 {std::string("帯電"), -1351}, {std::string("でし"), -1856}, {std::string("、と"), -558},
                 {std::string("また"), -2737}, {std::string("ただ"), -2687}, {std::string("くし"), -1520},
                 {std::string("るよ"), -944},  {std::string("いも"), 709},   {std::string("もあ"), -935},
                 {std::string("りも"), -1014}, {std::string("てあ"), -2039}, {std::string("たい"), -1183},
                 {std::string("てみ"), -1524}, {std::string("そこ"), -652},  {std::string("もし"), -490},
                 {std::string("てく"), -1248}, {std::string("ども"), -675},  {std::string("うど"), -1684},
                 {std::string("の前"), -820},  {std::string("のだ"), -873},  {std::string("なく"), -956},
                 {std::string("にな"), -362},  {std::string("人が"), 1674},  {std::string("んど"), -722},
                 {std::string("もの"), -753},  {std::string("いま"), -421},  {std::string("と思"), 545},
                 {std::string("れた"), -890},  {std::string("はい"), -770},  {std::string("すご"), -1196},
                 {std::string("くだ"), -1043}, {std::string("・・"), -1221}, {std::string("てき"), -1069},
                 {std::string("がっ"), -1494}, {std::string("はあ"), -1185}, {std::string("では"), -1027},
                 {std::string("いつ"), -659},  {std::string("とな"), 159},   {std::string("時間"), -681},
                 {std::string("がし"), 280},   {std::string("にし"), -458},  {std::string("うま"), -1227},
                 {std::string("たち"), -851},  {std::string("のお"), 458},   {std::string("ばい"), -968},
                 {std::string("、な"), -145},  {std::string("た時"), 421},   {std::string("のも"), -489},
                 {std::string("とか"), -782},  {std::string("らな"), -64},   {std::string("なか"), -299},
                 {std::string("のか"), -278},  {std::string("でな"), -1003}, {std::string("たも"), 318},
                 {std::string("とこ"), -337},  {std::string("もな"), -157},  {std::string("した"), -402},
                 {std::string("もつ"), -433},  {std::string("いい"), -357},  {std::string("ード"), -523},
                 {std::string("とき"), -230},  {std::string("もち"), -157},  {std::string("たよ"), -393},
                 {std::string("はで"), 41},    {std::string("とも"), -359},  {std::string("いし"), -401},
                 {std::string("いよ"), -494},  {std::string("はず"), -333},  {std::string("やす"), -524},
                 {std::string("と同"), -442},  {std::string("よう"), -175},  {std::string("いな"), -144},
                 {std::string("ーな"), 476},   {std::string("るの"), -197},  {std::string("しい"), -297},
                 {std::string("、１"), -643},  {std::string("ても"), -151},  {std::string("りな"), 191},
                 {std::string("がよ"), 195},   {std::string("の１"), -539},  {std::string("うか"), -137},
                 {std::string("、清"), -374},  {std::string("今日"), -360},  {std::string("とす"), -127},
                 {std::string("つの"), 186},   {std::string("］京"), -152},  {std::string("うい"), -93},
                 {std::string("のが"), -101},  {std::string("い人"), 80},    {std::string("けど"), -126},
                 {std::string("ーで"), 83},    {std::string("がち"), 62},    {std::string("の方"), 96},
                 {std::string("らい"), -54},   {std::string("でい"), -33},   {std::string("てた"), -37},
                 {std::string("どこ"), -20}},
                // param: BW3
                {{std::string("うま"), 4971},  {std::string("もの"), 3479},  {std::string("あり"), 1053},
                 {std::string("いた"), 712},   {std::string("よう"), -404},  {std::string("いう"), 719},
                 {std::string("上が"), 1571},  {std::string("ます"), -943},  {std::string("はじ"), 3173},
                 {std::string("とう"), -693},  {std::string("たま"), 1383},  {std::string("ちが"), 1979},
                 {std::string("いい"), 1237},  {std::string("おり"), -2875}, {std::string("のみ"), 3096},
                 {std::string("可能"), 402},   {std::string("ちゃ"), -1016}, {std::string("こと"), 899},
                 {std::string("そこ"), 647},   {std::string("でも"), 1643},  {std::string("その"), 1844},
                 {std::string("なっ"), -512},  {std::string("とい"), -1257}, {std::string("ある"), -339},
                 {std::string("この"), 1656},  {std::string("とき"), 1917},  {std::string("そう"), -1050},
                 {std::string("手に"), 1242},  {std::string("から"), -1223}, {std::string("持っ"), 1098},
                 {std::string("でき"), 980},   {std::string("かけ"), 2909},  {std::string("とて"), 2245},
                 {std::string("なる"), 481},   {std::string("はし"), 3011},  {std::string("ちょ"), 1986},
                 {std::string("して"), 278},   {std::string("とお"), 678},   {std::string("もら"), 2538},
                 {std::string("メー"), 364},   {std::string("ころ"), -190},  {std::string("そし"), -184},
                 {std::string("かか"), 1752},  {std::string("もう"), 2306},  {std::string("どん"), -397},
                 {std::string("・・"), -1499}, {std::string("より"), -1463}, {std::string("しま"), -93},
                 {std::string("とも"), 1038},  {std::string("めて"), -1778}, {std::string("もん"), 1078},
                 {std::string("いろ"), 832},   {std::string("まぁ"), 1442},  {std::string("だけ"), -941},
                 {std::string("した"), 813},   {std::string("さん"), -1566}, {std::string("うち"), 444},
                 {std::string("きっ"), 727},   {std::string("よく"), 1082},  {std::string("すご"), 897},
                 {std::string("以上"), -807},  {std::string("ない"), 287},   {std::string("ため"), 686},
                 {std::string("これ"), 1075},  {std::string("どう"), 296},   {std::string("はま"), 1041},
                 {std::string("す。"), -152},  {std::string("とっ"), 917},   {std::string("来た"), 408},
                 {std::string("しゃ"), 1283},  {std::string("かっ"), -802},  {std::string("ただ"), 1198},
                 {std::string("しい"), -519},  {std::string("すぐ"), 1094},  {std::string("もと"), 1264},
                 {std::string("やっ"), 422},   {std::string("かも"), -670},  {std::string("める"), -1304},
                 {std::string("電車"), 121},   {std::string("まし"), -670},  {std::string("いか"), 480},
                 {std::string("パソ"), 589},   {std::string("わか"), 691},   {std::string("なく"), 348},
                 {std::string("いる"), 556},   {std::string("とこ"), 742},   {std::string("中で"), 414},
                 {std::string("さい"), -672},  {std::string("みた"), -739},  {std::string("かつ"), 821},
                 {std::string("いて"), -372},  {std::string("なか"), 198},   {std::string("なら"), -160},
                 {std::string("だい"), 680},   {std::string("あっ"), -93},   {std::string("もっ"), 626},
                 {std::string("また"), -479},  {std::string("いや"), 732},   {std::string("考え"), 429},
                 {std::string("うか"), -268},  {std::string("もつ"), 666},   {std::string("まだ"), 296},
                 {std::string("きま"), -514},  {std::string("まで"), -677},  {std::string("お茶"), 627},
                 {std::string("こそ"), -520},  {std::string("とり"), 539},   {std::string("いら"), 621},
                 {std::string("です"), -239},  {std::string("まり"), -596},  {std::string("出来"), -428},
                 {std::string("つな"), 437},   {std::string("ほし"), -350},  {std::string("たい"), -238},
                 {std::string("ここ"), 552},   {std::string("はい"), 272},   {std::string("行き"), -218},
                 {std::string("楽し"), 128},   {std::string("し、"), -136},  {std::string("めっ"), 260},
                 {std::string("んは"), 438},   {std::string("出て"), 128},   {std::string("いま"), 85},
                 {std::string("つけ"), 251},   {std::string("みが"), -374},  {std::string("まず"), 233},
                 {std::string("だろ"), -357},  {std::string("ルー"), 249},   {std::string("がち"), -345},
                 {std::string("料理"), 8},     {std::string("祭り"), 214},   {std::string("使っ"), 109},
                 {std::string("と思"), -161},  {std::string("ぼく"), 329},   {std::string("イン"), 203},
                 {std::string("逆に"), 246},   {std::string("で、"), 119},   {std::string("どこ"), 46},
                 {std::string("ずっ"), 121},   {std::string("つい"), 62},    {std::string("ませ"), -58},
                 {std::string("あの"), 71},    {std::string("過ぎ"), -95},   {std::string("始め"), -28},
                 {std::string("まっ"), -24},   {std::string("程度"), -24},   {std::string("書い"), 12}},
                // param: TW1
                {{std::string("という"), 545},   {std::string("ていく"), 1686},  {std::string("ような"), 1298},
                 {std::string("・・・"), 1104},  {std::string("持って"), -1851}, {std::string("しかし"), 2079},
                 {std::string("てくれ"), 1444},  {std::string("のまま"), 1162},  {std::string("かなり"), 2083},
                 {std::string("やはり"), 1728},  {std::string("ながら"), 1223},  {std::string("ょうど"), 1174},
                 {std::string("もなく"), 947},   {std::string("思った"), 811},   {std::string("とんど"), 1250},
                 {std::string("、それ"), 412},   {std::string("ない、"), -1039}, {std::string("なんと"), -691},
                 {std::string("を利用"), -1017}, {std::string("がって"), -418},  {std::string("ひとつ"), 732},
                 {std::string("と思う"), 251},   {std::string("ました"), -268},  {std::string("である"), 267},
                 {std::string("かなか"), 698},   {std::string("そして"), 556},   {std::string("っかり"), 599},
                 {std::string("。ただ"), 676},   {std::string("リーグ"), 309},   {std::string("きない"), 141},
                 {std::string("はその"), -68},   {std::string("ちろん"), 196},   {std::string("くさん"), 225},
                 {std::string("ること"), -271},  {std::string("だって"), 164},   {std::string("なって"), -86},
                 {std::string("すごく"), 163},   {std::string("ろいろ"), 54},    {std::string("。その"), 16},
                 {std::string("くらい"), 4}},
                // param: TW2
                {{std::string("気に入"), -4086},
                 {std::string("ではな"), -1086},
                 {std::string("とがあ"), -1130},
                 {std::string("かもし"), -463},
                 {std::string("んでい"), -2306},
                 {std::string("そもそ"), -1441},
                 {std::string("うにな"), -803},
                 {std::string("してい"), -406},
                 {std::string("でもあ"), -936},
                 {std::string("ったこ"), -267},
                 {std::string("しかな"), 440},
                 {std::string("ともあ"), -757},
                 {std::string("からな"), -477},
                 {std::string("えるこ"), -436},
                 {std::string("でもな"), -207},
                 {std::string("とはい"), -59},
                 {std::string("えてい"), 50},
                 {std::string("してお"), -37}},
                // param: TW3
                {{std::string("という"), 970},   {std::string("もなく"), -1899}, {std::string("ところ"), -1724},
                 {std::string("として"), 655},   {std::string("、ある"), -2756}, {std::string("ている"), -1375},
                 {std::string("はない"), -473},  {std::string("のまま"), -961},  {std::string("すこと"), 710},
                 {std::string("てしま"), -1361}, {std::string("らない"), -1075}, {std::string("はそれ"), -1539},
                 {std::string("ていく"), -289},  {std::string("とした"), -1169}, {std::string("と言っ"), -1166},
                 {std::string("ていう"), 769},   {std::string("である"), -749},  {std::string("、なん"), -293},
                 {std::string("ること"), -49},   {std::string("であっ"), -812},  {std::string("となっ"), 229},
                 {std::string("なんで"), 574},   {std::string("いとこ"), 75},    {std::string("もいい"), -408},
                 {std::string("もあり"), -183},  {std::string("であり"), -535},  {std::string("ういう"), -120},
                 {std::string("ばいい"), -137},  {std::string("にして"), -37},   {std::string("ていた"), -66},
                 {std::string("るとき"), 108},   {std::string("でした"), -54},   {std::string("うこと"), -4}},
                // param: TW4
                {{std::string("ところ"), 2195},  {std::string("ように"), -1673}, {std::string("くらい"), 1598},
                 {std::string("した。"), -1569}, {std::string("ありま"), -1767}, {std::string("かなり"), 2848},
                 {std::string("できた"), 2069},  {std::string("ます。"), -1366}, {std::string("ような"), -2232},
                 {std::string("ことが"), -824},  {std::string("いた。"), 1066},  {std::string("だから"), 1092},
                 {std::string("うどん"), 1258},  {std::string("そうで"), -925},  {std::string("ことに"), -856},
                 {std::string("もちろ"), 1697},  {std::string("しかし"), 1383},  {std::string("ことで"), 380},
                 {std::string("ない。"), 191},   {std::string("ことも"), -588},  {std::string("あり、"), -595},
                 {std::string("ちなみ"), 1130},  {std::string("だった"), -1150}, {std::string("すると"), 406},
                 {std::string("こと。"), 683},   {std::string("でも、"), 628},   {std::string("いろい"), 590},
                 {std::string("いかな"), 651},   {std::string("メール"), 256},   {std::string("ようで"), -896},
                 {std::string("なかな"), 669},   {std::string("なくな"), 253},   {std::string("しない"), 438},
                 {std::string("ソフト"), 512},   {std::string("ことを"), 255},   {std::string("わけで"), -234},
                 {std::string("まって"), -824},  {std::string("なんと"), 481},   {std::string("すごい"), 314},
                 {std::string("してき"), 278},   {std::string("いえば"), 397},   {std::string("らしい"), 424},
                 {std::string("しかも"), 494},   {std::string("ことは"), -232},  {std::string("あたり"), -390},
                 {std::string("食べて"), 140},   {std::string("しても"), -174},  {std::string("できま"), 52},
                 {std::string("なんか"), 116},   {std::string("なんて"), -102},  {std::string("いくら"), 170},
                 {std::string("観光客"), -75},   {std::string("いいと"), -63},   {std::string("いる。"), 37},
                 {std::string("ちょっ"), 20},    {std::string("そうい"), 16}},
                // param: UW1
                {{std::string("は"), -273}, {std::string("う"), 275},   {std::string("ま"), 128},  {std::string("お"), 922},
                 {std::string("ご"), 890},  {std::string("と"), 165},   {std::string("が"), -385}, {std::string("る"), -34},
                 {std::string("せ"), 210},  {std::string("い"), -91},   {std::string("ん"), 289},  {std::string("あ"), -230},
                 {std::string("で"), -127}, {std::string("学"), 209},   {std::string("り"), -102}, {std::string("浮"), 1464},
                 {std::string("に"), -344}, {std::string("甘"), -1424}, {std::string("つ"), 241},  {std::string("バ"), 511},
                 {std::string("な"), -220}, {std::string("て"), 60},    {std::string("水"), 1969}, {std::string("、"), -26},
                 {std::string("電"), 127},  {std::string("当"), -1038}, {std::string("ふ"), 1899}, {std::string("ら"), 72},
                 {std::string("れ"), -44},  {std::string("携"), -86},   {std::string("を"), -176}, {std::string("そ"), 137},
                 {std::string("っ"), 194},  {std::string("ろ"), 303},   {std::string("［"), -601}, {std::string("ー"), 113},
                 {std::string("か"), -110}, {std::string("間"), 572},   {std::string("ち"), 285},  {std::string("ゆ"), -428},
                 {std::string("し"), -30},  {std::string("外"), 301},   {std::string("フ"), -155}, {std::string("も"), -96},
                 {std::string("０"), 275},  {std::string("空"), -524},  {std::string("ス"), -251}, {std::string("く"), 134},
                 {std::string("自"), 412},  {std::string("す"), 151},   {std::string("用"), 599},  {std::string("さ"), -164},
                 {std::string("チ"), 183},  {std::string("ケ"), -196},  {std::string("入"), 266},  {std::string("ツ"), 134},
                 {std::string("困"), 574},  {std::string("利"), -371},  {std::string("生"), 254},  {std::string("機"), 318},
                 {std::string("安"), -400}, {std::string("画"), -53},   {std::string("庭"), 619},  {std::string("イ"), 211},
                 {std::string("３"), -258}, {std::string("メ"), 96},    {std::string("面"), -306}, {std::string("何"), 173},
                 {std::string("こ"), 64},   {std::string("問"), 588},   {std::string("方"), 124},  {std::string("白"), -248},
                 {std::string("じ"), -49},  {std::string("社"), 225},   {std::string("様"), 365},  {std::string("田"), 137},
                 {std::string("国"), -382}, {std::string("込"), 42},    {std::string("の"), -31},  {std::string("高"), 170},
                 {std::string("。"), -17},  {std::string("ッ"), 117},   {std::string("だ"), 63},   {std::string("新"), 178},
                 {std::string("．"), -72},  {std::string("ラ"), 92},    {std::string("使"), -79},  {std::string("見"), 76},
                 {std::string("？"), 113},  {std::string("振"), 209},   {std::string("！"), 65},   {std::string("撮"), -182},
                 {std::string("券"), 79},   {std::string("ざ"), 120},   {std::string("周"), 137},  {std::string("長"), 144},
                 {std::string("や"), -42},  {std::string("山"), 114},   {std::string("パ"), 63},   {std::string("好"), 50},
                 {std::string("ペ"), 126},  {std::string("着"), -16},   {std::string("め"), -12},  {std::string("み"), -8},
                 {std::string("個"), -79},  {std::string("上"), 12},    {std::string("え"), -8},   {std::string("連"), -29},
                 {std::string("ボ"), 16}},
                // param: UW2
                {{std::string("。"), -1401}, {std::string("、"), -1370}, {std::string("を"), -2403}, {std::string("に"), -1207},
                 {std::string("が"), -653},  {std::string("は"), -1010}, {std::string("か"), 18},    {std::string("れ"), 5},
                 {std::string("っ"), 269},   {std::string("以"), 2215},  {std::string("て"), -985},  {std::string("う"), -489},
                 {std::string("全"), 1762},  {std::string("の"), -695},  {std::string("そ"), -534},  {std::string("で"), -810},
                 {std::string("だ"), 523},   {std::string("ゆ"), 1668},  {std::string("さ"), 922},   {std::string("く"), -812},
                 {std::string("め"), 81},    {std::string("と"), -751},  {std::string("も"), -813},  {std::string("あ"), -233},
                 {std::string("一"), 1197},  {std::string("し"), -49},   {std::string("ん"), 344},   {std::string("お"), -711},
                 {std::string("食"), 981},   {std::string("ご"), -682},  {std::string("き"), -556},  {std::string("毎"), 1671},
                 {std::string("結"), 1952},  {std::string("彼"), 754},   {std::string("少"), 676},   {std::string("最"), 445},
                 {std::string("ほ"), 1001},  {std::string("わ"), -118},  {std::string("舞"), 2257},  {std::string("上"), -421},
                 {std::string("よ"), 577},   {std::string("同"), 567},   {std::string("り"), -479},  {std::string("機"), 1341},
                 {std::string("人"), 201},   {std::string("意"), 531},   {std::string("な"), -492},  {std::string("「"), -482},
                 {std::string("ば"), -464},  {std::string("関"), 745},   {std::string("京"), -377},  {std::string("本"), 694},
                 {std::string("い"), -79},   {std::string("大"), 266},   {std::string("目"), -1004}, {std::string("多"), 387},
                 {std::string("着"), -477},  {std::string("つ"), -423},  {std::string("ケ"), -246},  {std::string("振"), -1313},
                 {std::string("ゃ"), 283},   {std::string("題"), 848},   {std::string("手"), 663},   {std::string("ひ"), -1353},
                 {std::string("容"), 956},   {std::string("水"), 335},   {std::string("我"), -1421}, {std::string("る"), -207},
                 {std::string("裏"), -1437}, {std::string("ー"), 274},   {std::string("ぜ"), 567},   {std::string("ぱ"), 396},
                 {std::string("名"), 341},   {std::string("フ"), -264},  {std::string("寺"), -551},  {std::string("葉"), 787},
                 {std::string("ま"), -173},  {std::string("夕"), 826},   {std::string("ぶ"), 435},   {std::string("絶"), 1181},
                 {std::string("高"), 498},   {std::string("今"), 276},   {std::string("友"), 494},   {std::string("ら"), -91},
                 {std::string("ン"), 167},   {std::string("た"), -109},  {std::string("み"), -123},  {std::string("料"), 70},
                 {std::string("イ"), -122},  {std::string("電"), 315},   {std::string("冷"), -664},  {std::string("打"), 557},
                 {std::string("メ"), -47},   {std::string("世"), -793},  {std::string("パ"), 289},   {std::string("女"), -487},
                 {std::string("ｒ"), 990},   {std::string("プ"), -195},  {std::string("取"), -360},  {std::string("＾"), 149},
                 {std::string("場"), 190},   {std::string("こ"), 161},   {std::string("，"), -306},  {std::string("落"), -499},
                 {std::string("選"), 313},   {std::string("知"), -361},  {std::string("極"), 748},   {std::string("入"), -160},
                 {std::string("良"), 183},   {std::string("ラ"), -210},  {std::string("ス"), 54},    {std::string("遊"), -310},
                 {std::string("用"), -161},  {std::string("式"), 93},    {std::string("々"), 80},    {std::string("車"), 124},
                 {std::string("立"), -292},  {std::string("下"), 154},   {std::string("ル"), 31},    {std::string("甘"), 227},
                 {std::string("実"), 97},    {std::string("重"), 159},   {std::string("乗"), -115},  {std::string("当"), 94},
                 {std::string("："), 106},   {std::string("］"), -50},   {std::string("Ｈ"), -84},   {std::string("的"), 42},
                 {std::string("相"), 75},    {std::string("三"), 58},    {std::string("け"), 16},    {std::string("格"), 130},
                 {std::string("正"), 100},   {std::string("［"), -16},   {std::string("日"), -25},   {std::string("公"), -33},
                 {std::string("４"), 20},    {std::string("ィ"), -12},   {std::string("ろ"), -4}},
                // param: UW3
                {{std::string("。"), 6699},  {std::string("に"), 3897},  {std::string("、"), 4784},  {std::string("の"), 3706},
                 {std::string("が"), 4162},  {std::string("を"), 5769},  {std::string("は"), 4221},  {std::string("と"), 2900},
                 {std::string("る"), 2971},  {std::string("く"), 2902},  {std::string("も"), 3155},  {std::string("う"), 2242},
                 {std::string("て"), 2447},  {std::string("で"), 3372},  {std::string("た"), 2217},  {std::string("い"), 1855},
                 {std::string("な"), 2357},  {std::string("っ"), -1853}, {std::string("方"), 2814},  {std::string("ら"), 1353},
                 {std::string("ん"), 967},   {std::string("ば"), 1790},  {std::string("］"), 2166},  {std::string("か"), 1899},
                 {std::string("，"), 3358},  {std::string("り"), 1013},  {std::string("！"), 3252},  {std::string("ー"), -102},
                 {std::string("や"), 2149},  {std::string("？"), 3703},  {std::string("．"), 2093},  {std::string("・"), 1074},
                 {std::string("…"), 2428},   {std::string("部"), 1732},  {std::string("ど"), 992},   {std::string("ご"), -2327},
                 {std::string("）"), 2573},  {std::string("ッ"), -2137}, {std::string("☆"), 2675},   {std::string("お"), -1495},
                 {std::string("上"), 428},   {std::string("以"), -1870}, {std::string("つ"), 1078},  {std::string("」"), 1608},
                 {std::string("♪"), 2714},   {std::string("電"), -1669}, {std::string("ク"), 335},   {std::string("だ"), 866},
                 {std::string("へ"), 2073},  {std::string("ろ"), 1142},  {std::string("笑"), 2335},  {std::string("ず"), 1456},
                 {std::string("面"), 475},   {std::string("び"), 514},   {std::string("あ"), 1179},  {std::string("今"), 1080},
                 {std::string("ぐ"), 2053},  {std::string("分"), 1111},  {std::string("感"), 1389},  {std::string("大"), -1134},
                 {std::string("京"), -1396}, {std::string("中"), 998},   {std::string("人"), 486},   {std::string("場"), -794},
                 {std::string("イ"), -568},  {std::string("す"), 938},   {std::string("さ"), -599},  {std::string("ま"), -370},
                 {std::string("利"), -681},  {std::string("間"), 752},   {std::string("０"), -870},  {std::string("ぁ"), 1322},
                 {std::string("フ"), -1285}, {std::string("ン"), -284},  {std::string("「"), -1434}, {std::string("当"), -337},
                 {std::string("き"), 530},   {std::string("日"), 713},   {std::string("ス"), -901},  {std::string("ゃ"), 1112},
                 {std::string("後"), 1224},  {std::string("々"), 1435},  {std::string("シ"), -1196}, {std::string("度"), 982},
                 {std::string("観"), -976},  {std::string("食"), -517},  {std::string("行"), -725},  {std::string("ド"), -995},
                 {std::string("リ"), -636},  {std::string("え"), 728},   {std::string("空"), 902},   {std::string("夜"), 1480},
                 {std::string("ア"), -700},  {std::string("』"), 1404},  {std::string("１"), -550},  {std::string("体"), 1000},
                 {std::string("秋"), 1464},  {std::string("入"), -819},  {std::string("プ"), -718},  {std::string("昔"), 1287},
                 {std::string("［"), -960},  {std::string("題"), 1113},  {std::string("能"), -710},  {std::string("皆"), 1294},
                 {std::string("む"), 920},   {std::string("学"), -552},  {std::string("態"), -749},  {std::string("月"), 584},
                 {std::string("係"), 701},   {std::string("変"), 328},   {std::string("超"), 976},   {std::string("ぶ"), 672},
                 {std::string("然"), 515},   {std::string("〜"), 489},   {std::string("れ"), 295},   {std::string("由"), 680},
                 {std::string("段"), 13},    {std::string("非"), 768},   {std::string("光"), -218},  {std::string("意"), -477},
                 {std::string("ぞ"), 825},   {std::string("年"), 344},   {std::string("べ"), -711},  {std::string("機"), -463},
                 {std::string("言"), -419},  {std::string("ち"), 363},   {std::string("気"), 130},   {std::string("み"), 275},
                 {std::string("ｏ"), -520},  {std::string("＞"), 588},   {std::string("し"), 181},   {std::string("け"), 159},
                 {std::string("移"), -635},  {std::string("見"), 160},   {std::string("ズ"), 304},   {std::string("自"), -352},
                 {std::string("果"), 767},   {std::string("番"), 252},   {std::string("色"), 469},   {std::string("　"), 257},
                 {std::string("ぱ"), 454},   {std::string("出"), -160},  {std::string("屋"), 338},   {std::string("カ"), -102},
                 {std::string("メ"), -136},  {std::string("指"), -240},  {std::string("店"), 203},   {std::string("一"), -50},
                 {std::string("別"), 285},   {std::string("頭"), 486},   {std::string("朝"), 270},   {std::string("想"), 398},
                 {std::string("味"), 101},   {std::string("生"), -160},  {std::string("語"), 159},   {std::string("”"), 215},
                 {std::string("着"), -149},  {std::string("所"), 189},   {std::string("："), 94},    {std::string("神"), -111},
                 {std::string("応"), 149},   {std::string("程"), 145},   {std::string("不"), -93},   {std::string("料"), -76},
                 {std::string("寺"), 50},    {std::string("水"), 54},    {std::string("レ"), -54},   {std::string("パ"), -29},
                 {std::string("サ"), 33},    {std::string("グ"), 12},    {std::string("有"), -16}},
                // param: UW4
                {{std::string("。"), -7440}, {std::string("の"), -4018}, {std::string("が"), -3577}, {std::string("に"), -4299},
                 {std::string("て"), -3839}, {std::string("る"), -5462}, {std::string("、"), -7452}, {std::string("は"), -3332},
                 {std::string("っ"), -4313}, {std::string("で"), -3120}, {std::string("を"), -4861}, {std::string("う"), -2446},
                 {std::string("と"), -2917}, {std::string("り"), -4081}, {std::string("ま"), -1296}, {std::string("た"), -1675},
                 {std::string("あ"), 501},   {std::string("れ"), -4326}, {std::string("な"), -1928}, {std::string("そ"), 456},
                 {std::string("く"), -2884}, {std::string("か"), -2662}, {std::string("ら"), -4391}, {std::string("ご"), 591},
                 {std::string("し"), -1725}, {std::string("こ"), -517},  {std::string("だ"), -2037}, {std::string("き"), -2074},
                 {std::string("い"), -1531}, {std::string("ん"), -3821}, {std::string("ー"), -2899}, {std::string("も"), -2746},
                 {std::string("み"), -1111}, {std::string("食"), 652},   {std::string("行"), 411},   {std::string("思"), 1386},
                 {std::string("す"), -1159}, {std::string("空"), 2526},  {std::string("大"), 788},   {std::string("」"), -5393},
                 {std::string("じ"), -2352}, {std::string("や"), -1257}, {std::string("け"), -3441}, {std::string("め"), -1867},
                 {std::string("さ"), -1716}, {std::string("よ"), -643},  {std::string("「"), 2301},  {std::string("表"), 1003},
                 {std::string("日"), 695},   {std::string("広"), 1811},  {std::string("場"), 333},   {std::string("一"), 576},
                 {std::string("時"), 564},   {std::string("ち"), -1762}, {std::string("冷"), 2351},  {std::string("京"), 614},
                 {std::string("，"), -4205}, {std::string("わ"), -1624}, {std::string("人"), 512},   {std::string("私"), 1957},
                 {std::string("！"), -4469}, {std::string("え"), -1844}, {std::string("ッ"), -2189}, {std::string("当"), 384},
                 {std::string("・"), -677},  {std::string("ン"), -2078}, {std::string("１"), 710},   {std::string("方"), -816},
                 {std::string("べ"), -2964}, {std::string("手"), 270},   {std::string("来"), 430},   {std::string("ろ"), -2793},
                 {std::string("せ"), -1498}, {std::string("ル"), -1178}, {std::string("ば"), -2432}, {std::string("つ"), -1195},
                 {std::string("使"), 1131},  {std::string("（"), 2399},  {std::string("持"), 180},   {std::string("…"), -2208},
                 {std::string("ゆ"), -2265}, {std::string("？"), -3412}, {std::string("）"), -4207}, {std::string("ぶ"), -2267},
                 {std::string("何"), 1291},  {std::string("彼"), 1247},  {std::string("び"), -1619}, {std::string("笑"), -3444},
                 {std::string("本"), -1249}, {std::string("ど"), -697},  {std::string("［"), 1760},  {std::string("．"), -2874},
                 {std::string("言"), 227},   {std::string("お"), 820},   {std::string("ず"), -1966}, {std::string("イ"), -507},
                 {std::string("今"), 1002},  {std::string("ゃ"), -2441}, {std::string("見"), 386},   {std::string("自"), 792},
                 {std::string("２"), 533},   {std::string("最"), 1072},  {std::string("用"), -716},  {std::string("帯"), -1138},
                 {std::string("間"), -393},  {std::string("携"), 441},   {std::string("多"), 1062},  {std::string("リ"), -707},
                 {std::string("能"), -1270}, {std::string("』"), -3209}, {std::string("］"), -1427}, {std::string("気"), 235},
                 {std::string("入"), 412},   {std::string("有"), 744},   {std::string("ね"), -1659}, {std::string("白"), 451},
                 {std::string("ぁ"), -1501}, {std::string("ぎ"), -1428}, {std::string("中"), 34},    {std::string("ひ"), 1076},
                 {std::string("遊"), 1409},  {std::string("”"), -817},   {std::string("風"), 673},   {std::string("コ"), 344},
                 {std::string("ょ"), -1527}, {std::string("水"), 286},   {std::string("情"), -375},  {std::string("０"), -374},
                 {std::string("む"), -1261}, {std::string("合"), -948},  {std::string("公"), 724},   {std::string("ぼ"), -949},
                 {std::string("♪"), -1513},  {std::string("小"), 736},   {std::string("僕"), 856},   {std::string("☆"), -1296},
                 {std::string("〜"), -1156}, {std::string("ド"), -76},   {std::string("楽"), 308},   {std::string("全"), 475},
                 {std::string("書"), 411},   {std::string("ス"), -218},  {std::string("二"), 481},   {std::string("態"), -582},
                 {std::string("少"), 436},   {std::string("不"), 505},   {std::string("返"), -347},  {std::string("定"), -356},
                 {std::string("ぜ"), -907},  {std::string("高"), 229},   {std::string("特"), 623},   {std::string("祭"), 413},
                 {std::string("他"), 368},   {std::string("づ"), -776},  {std::string("目"), 117},   {std::string("ぞ"), -935},
                 {std::string("話"), 316},   {std::string("子"), -233},  {std::string("ぐ"), -840},  {std::string("年"), -625},
                 {std::string("３"), 22},    {std::string("道"), 181},   {std::string("的"), -500},  {std::string("ｏ"), -489},
                 {std::string("実"), 368},   {std::string("買"), 366},   {std::string("無"), 192},   {std::string("街"), 443},
                 {std::string("東"), 470},   {std::string("物"), -204},  {std::string("ュ"), -434},  {std::string("ほ"), -176},
                 {std::string("込"), -568},  {std::string("甘"), 383},   {std::string("タ"), -212},  {std::string("換"), -278},
                 {std::string("現"), 191},   {std::string("新"), 150},   {std::string("夏"), 403},   {std::string("フ"), -157},
                 {std::string("ト"), -148},  {std::string("げ"), -455},  {std::string("ざ"), -327},  {std::string("デ"), 174},
                 {std::string("券"), -471},  {std::string("感"), 28},    {std::string("秋"), 307},   {std::string("難"), 179},
                 {std::string("外"), 153},   {std::string("へ"), -247},  {std::string("ョ"), -156},  {std::string("流"), 254},
                 {std::string("舞"), 138},   {std::string("サ"), 75},    {std::string("前"), -75},   {std::string("店"), 101},
                 {std::string("押"), 264},   {std::string("開"), 61},    {std::string("　"), -148},  {std::string("＾"), -256},
                 {std::string("度"), -125},  {std::string("５"), 52},    {std::string("々"), -142},  {std::string("写"), 159},
                 {std::string("回"), -154},  {std::string("ラ"), -56},   {std::string("関"), -145},  {std::string("安"), 63},
                 {std::string("相"), 54},    {std::string("参"), 45},    {std::string("百"), 45},    {std::string("取"), -45},
                 {std::string("ム"), -41},   {std::string("屋"), -8},    {std::string("通"), -8},    {std::string("勝"), 4},
                 {std::string("美"), 4}},
                // param: UW5
                {{std::string("。"), -2177}, {std::string("で"), -955},  {std::string("す"), -681},  {std::string("、"), -1011},
                 {std::string("な"), -608},  {std::string("ま"), -353},  {std::string("て"), 169},   {std::string("っ"), 964},
                 {std::string("る"), 175},   {std::string("は"), -874},  {std::string("き"), 1177},  {std::string("し"), -394},
                 {std::string("お"), 345},   {std::string("を"), -674},  {std::string("く"), 287},   {std::string("こ"), 500},
                 {std::string("じ"), 886},   {std::string("に"), -612},  {std::string("そ"), -421},  {std::string("能"), 219},
                 {std::string("わ"), 710},   {std::string("べ"), 1871},  {std::string("え"), 637},   {std::string("ん"), 1001},
                 {std::string("あ"), -271},  {std::string("た"), 198},   {std::string("み"), 293},   {std::string("い"), 345},
                 {std::string("・"), -1082}, {std::string("と"), -617},  {std::string("よ"), -587},  {std::string("の"), -641},
                 {std::string("ろ"), -360},  {std::string("上"), -1087}, {std::string("か"), 210},   {std::string("だ"), -338},
                 {std::string("め"), 851},   {std::string("帯"), 303},   {std::string("れ"), 495},   {std::string("ざ"), 1494},
                 {std::string("ら"), 222},   {std::string("ず"), 1173},  {std::string("さ"), -327},  {std::string("つ"), 1091},
                 {std::string("ル"), -472},  {std::string("面"), 776},   {std::string("」"), -1068}, {std::string("電"), -285},
                 {std::string("ぼ"), 1415},  {std::string("日"), 342},   {std::string("が"), -272},  {std::string("び"), 826},
                 {std::string("せ"), -303},  {std::string("思"), -891},  {std::string("ち"), 572},   {std::string("冷"), 1123},
                 {std::string("り"), 409},   {std::string("年"), 876},   {std::string("使"), -1390}, {std::string("利"), 365},
                 {std::string("葉"), 791},   {std::string("！"), -384},  {std::string("］"), -470},  {std::string("合"), 255},
                 {std::string("ぶ"), 15},    {std::string("券"), -1133}, {std::string("意"), 708},   {std::string("ぐ"), 159},
                 {std::string("バ"), -254},  {std::string("も"), -93},   {std::string("う"), 325},   {std::string("入"), -341},
                 {std::string("移"), -571},  {std::string("ト"), -313},  {std::string("体"), -1085}, {std::string("当"), 401},
                 {std::string("々"), 505},   {std::string("分"), 173},   {std::string("イ"), 171},   {std::string("見"), -272},
                 {std::string("来"), -122},  {std::string("料"), 579},   {std::string("寺"), -461},  {std::string("ぎ"), 348},
                 {std::string("手"), 179},   {std::string("続"), -872},  {std::string("む"), 458},   {std::string("通"), -209},
                 {std::string("．"), -184},  {std::string("タ"), 244},   {std::string("行"), -180},  {std::string("？"), -192},
                 {std::string("水"), -154},  {std::string("先"), -562},  {std::string("都"), 40},    {std::string("一"), -151},
                 {std::string("ど"), -41},   {std::string("ば"), 209},   {std::string("ア"), -123},  {std::string("学"), 49},
                 {std::string("最"), -116},  {std::string("降"), 104},   {std::string("ｏ"), 95},    {std::string("へ"), -146},
                 {std::string("何"), -176},  {std::string("効"), 111},   {std::string("ン"), -30},   {std::string("ょ"), 90},
                 {std::string("ー"), 4},     {std::string("　"), -135},  {std::string("（"), -67},   {std::string("種"), 42},
                 {std::string("７"), -101},  {std::string("的"), -54},   {std::string("成"), 46},    {std::string("ラ"), 29},
                 {std::string("Ｎ"), 104},   {std::string("１"), -29},   {std::string("有"), -37},   {std::string("中"), 8},
                 {std::string("場"), 4}},
                // param: UW6
                {{std::string("が"), 320},  {std::string("。"), -307},  {std::string("て"), -16},  {std::string("で"), 219},
                 {std::string("は"), 307},  {std::string("し"), 581},   {std::string("入"), 621},  {std::string("ど"), 828},
                 {std::string("あ"), -496}, {std::string("空"), 1589},  {std::string("な"), 218},  {std::string("す"), -90},
                 {std::string("だ"), 95},   {std::string("め"), 1415},  {std::string("券"), 1711}, {std::string("さ"), 555},
                 {std::string("ご"), -283}, {std::string("の"), 85},    {std::string("性"), 2064}, {std::string("う"), 35},
                 {std::string("や"), 819},  {std::string("り"), 578},   {std::string("場"), -864}, {std::string("に"), 245},
                 {std::string("つ"), 506},  {std::string("ろ"), 352},   {std::string("き"), -17},  {std::string("っ"), 301},
                 {std::string("る"), 71},   {std::string("か"), 231},   {std::string("い"), 365},  {std::string("ら"), 65},
                 {std::string("そ"), -101}, {std::string("ば"), 527},   {std::string("け"), -213}, {std::string("ー"), -66},
                 {std::string("ん"), 324},  {std::string("彼"), -1272}, {std::string("ク"), -346}, {std::string("ル"), 207},
                 {std::string("０"), 626},  {std::string("く"), 240},   {std::string("、"), 180},  {std::string("食"), -284},
                 {std::string("遊"), -906}, {std::string("寺"), 611},   {std::string("・"), -639}, {std::string("："), 1217},
                 {std::string("言"), -361}, {std::string("ゆ"), 755},   {std::string("態"), 221},  {std::string("込"), 679},
                 {std::string("を"), 85},   {std::string("的"), 479},   {std::string("可"), 567},  {std::string("タ"), 380},
                 {std::string("気"), 415},  {std::string("思"), -111},  {std::string("ぱ"), 813},  {std::string("ま"), 170},
                 {std::string("メ"), 239},  {std::string("お"), -18},   {std::string("ピ"), 780},  {std::string("カ"), 292},
                 {std::string("送"), -896}, {std::string("来"), -261},  {std::string("過"), 846},  {std::string("イ"), -244},
                 {std::string("効"), -725}, {std::string("シ"), -130},  {std::string("ケ"), -388}, {std::string("ず"), -403},
                 {std::string("ぶ"), -248}, {std::string("焼"), 643},   {std::string("れ"), 119},  {std::string("広"), -150},
                 {std::string("機"), 216},  {std::string("わ"), 60},    {std::string("ン"), -64},  {std::string("方"), -235},
                 {std::string("１"), 33},   {std::string("こ"), 41},    {std::string("店"), 164},  {std::string("印"), 360},
                 {std::string("び"), 129},  {std::string("回"), -94},   {std::string("ぎ"), 280},  {std::string("不"), 204},
                 {std::string("も"), -18},  {std::string("自"), 123},   {std::string("む"), 168},  {std::string("パ"), -112},
                 {std::string("周"), 275},  {std::string("出"), 68},    {std::string("参"), 114},  {std::string("神"), 33},
                 {std::string("着"), -20},  {std::string("間"), -4},    {std::string("練"), 8},    {std::string("ゃ"), -4}},

            },

        }};
    return model;
}
} // namespace budoux
